root: true
env:
  node: true
extends:
  - plugin:vue/vue3-essential
  - eslint:recommended
  - "@vue/typescript/recommended"
parserOptions:
  ecmaVersion: 2020
rules:
  no-console: warn
  no-debugger: error
  indent: off
  vue/script-indent: off
    # ['warn', 2, { baseIndent: 1 }]
  vue/html-indent: off
  #   ['error', 2, {
  #   attribute: 1,
  #   baseIndent: 1,
  #   closeBracket: 0,
  #   alignAttributesVertically: true,
  #   ignores: []
  # }]

