name: "🚀 deploy CI"
on:
  push:
    branches:
      - demo
      - test
      - dev1
      - dev2
      - dev3
    paths-ignore:
      - 'README*'

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get code
        uses: actions/checkout@v2
      - name: 🚚 Get node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: 🚚 Get deps
        run: |
          npm install &&
          npm ls -a
      ## Build stage need to be kept before configuration to test the
      ## released file still offer dynamic configuration.
      - name: 🔨 Build
        run: |
          npm run build
      - name: 🔨 Config
        run: |
          rm dist/config.sample.json
          echo "{
            \"appName\": \"Monujo-CI-${GITHUB_REF_NAME}\",
            \"lokapiDb\": \"odoo\",
            \"lokapiHost\": \"${GITHUB_REF_NAME}.lokavaluto.fr\",
            \"mapUrl\": \"https://carte.${GITHUB_REF_NAME}.lokavaluto.fr\",
            \"logoUrl\": \"https://monujo.${GITHUB_REF_NAME}.lokavaluto.fr/img/logo.png\",
            \"loginLogoUrl\": \"https://monujo.${GITHUB_REF_NAME}.lokavaluto.fr/img/logo.png\",
            \"locales\": {
              \"availableLanguages\": {
                \"en-US\": {
                  \"label\": \"English (US)\"
                },
                \"fr-FR\": {
                  \"label\": \"Français (France)\",
                  \"url\": \"https://docker.0k.io/downloads/monujo.fr-FR.json\"
                }
              },
              \"appStringsLanguage\": \"en-US\",
              \"defaultLanguage\": \"en-US\"
            }
          }" > dist/config.json
          cat dist/config.json
      - name: "📂 SFTP Sync files"
        uses: swillner/sftp-sync-action@v1.0
        with:
          server: ${{ github.ref_name }}.lokavaluto.fr
          port: 10322
          user: monujo
          user_private_key: ${{ secrets.sftp_private_key }}
          host_public_key:
          local: ./dist/
          remote: /monujo
          mirror_options: "--verbose"
