name: "🚀 Github Release"
on:
  push:
    tags:
      - '[0-9]+.[0-9].+[0-9]+'
      - '[0-9]+.[0-9].+[0-9]+-rc.[0-9]+'

jobs:
  deploy:
    name: Github Release
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get code
        uses: actions/checkout@v2
      - name: Setup java
        uses: actions/setup-java@v1
        with:
            distribution: 'zulu'
            java-version: '11'
      - name: 🚚 Get node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: 🚚 Create assets and github release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_KEYSTORE: ${{ secrets.RELEASE_KEYSTORE }}
          RELEASE_KEYSTORE_PASSWORD: ${{ secrets.RELEASE_KEYSTORE_PASSWORD }}
        run: |
          pip install gitchangelog pystache &&
          npm install -g semver &&
          bin/release -P -d
